#pragma config(Hubs,	S1, HTMotor,	HTMotor,	HTMotor,	HTMotor)
#pragma config(Hubs,	S2, HTServo,	none,			none,			none)
#pragma config(Sensor, S3,		 ultrason,			 sensorSONAR)
#pragma config(Motor,	 mtr_S1_C1_1,			motora,				 tmotorTetrix, openLoop)
#pragma config(Motor,	 mtr_S1_C1_2,			motorb,				 tmotorTetrix, openLoop)
#pragma config(Motor,	 mtr_S1_C2_1,			motorfrontleft, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,	 mtr_S1_C2_2,			motorbackleft, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,	 mtr_S1_C3_1,			motorfrontright, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,	 mtr_S1_C3_2,			motorbackright, tmotorTetrix, openLoop)
#pragma config(Motor,	 mtr_S1_C4_1,			motorJ,				 tmotorTetrix, openLoop)
#pragma config(Motor,	 mtr_S1_C4_2,			motorK,				 tmotorTetrix, openLoop)
#pragma config(Servo,	 srvo_S2_C1_1,		servograb,						tServoStandard)
#pragma config(Servo,	 srvo_S2_C1_2,		servoauto,						tServoStandard)
#pragma config(Servo,	 srvo_S2_C1_3,		servo3,								tServoNone)
#pragma config(Servo,	 srvo_S2_C1_4,		servo4,								tServoNone)
#pragma config(Servo,	 srvo_S2_C1_5,		servo5,								tServoNone)
#pragma config(Servo,	 srvo_S2_C1_6,		servo6,								tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//													 Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"	 //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//																		initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//	 1. Move motors and servos to a preset position.
//	 2. Some sensor types take a short while to reach stable values during which time it is best that
//			robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//			"bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
void mov1();void allstop(); void turnright(float angle);
void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.


	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//																				 Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//	 1. Have the robot follow a line on the game field until it reaches one of the puck storage
//			areas.
//	 2. Load pucks into the robot from the storage bin.
//	 3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.

	///////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////
	////																									 ////
	////		Add your robot specific autonomous code here.	 ////
	////																									 ////
	///////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////
	PlaySound(soundBlip);
	turnright(90.0);
}

void mov1(){
	nMotorEncoder[motorfrontleft]=0;
	while (nMotorEncoder[motorfrontleft]<2800){
		motor[motorfrontleft]=-50;
		motor[motorfrontright]=-50;
		motor[motorbackleft]=-50;
		motor[motorbackright]=-50;
	}
	PlaySound(soundBlip);
	while (nMotorEncoder[motorfrontleft]<2979){
		motor[motorfrontleft]=-20;
		motor[motorfrontright]=-20;
		motor[motorbackleft]=-20;
		motor[motorbackright]=-20;
	}
	PlaySound(soundBlip);
	allstop();

}
void allstop(){
	PlaySound(soundBlip);
motor[motorfrontleft]=0;
motor[motorfrontright]=0;
motor[motorbackleft]=0;
motor[motorbackright]=0;
}
void turnright(float angle){ //angle in degrees
float dist;
//dist=PI*18.0*sqrt(2.0)*(angle/360.0);
//dist=dist/(3.0*PI);
//dist=dist*360.0*4.0+100.0;
dist=3400;
dist=(angle*3400/90.0);
nMotorEncoder[motorfrontleft]=0;
while (nMotorEncoder[motorfrontleft]<dist){
motor[motorfrontleft]=50;
motor[motorfrontright]=-50;
motor[motorbackleft]=50;
motor[motorbackright]=-50;
}
allstop();
}
